"""Event type constants for AuditLog rows (§54). Plain strings, not an Enum,
because AuditLog.event_type is unconstrained by design — new event types
shouldn't require a migration."""

OTP_REQUESTED = "OTP_REQUESTED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILURE = "LOGIN_FAILURE"
LOGOUT = "LOGOUT"

SHARE_SESSION_CREATED = "SHARE_SESSION_CREATED"
SHARE_SESSION_REVOKED = "SHARE_SESSION_REVOKED"
SHARE_OTP_REQUESTED = "SHARE_OTP_REQUESTED"
SHARE_AUTHENTICATED = "SHARE_AUTHENTICATED"
SHARE_AUTH_FAILURE = "SHARE_AUTH_FAILURE"
SHARE_VIEWED = "SHARE_VIEWED"
ACCESS_REQUESTED = "ACCESS_REQUESTED"
PERMISSION_GRANTED = "PERMISSION_GRANTED"
PERMISSION_DECLINED = "PERMISSION_DECLINED"
