"""Event type constants for AuditLog rows (§54). Plain strings, not an Enum,
because AuditLog.event_type is unconstrained by design — new event types
shouldn't require a migration."""

OTP_REQUESTED = "OTP_REQUESTED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILURE = "LOGIN_FAILURE"
REGISTER_FAILURE = "REGISTER_FAILURE"
LOGOUT = "LOGOUT"

SHARE_SESSION_CREATED = "SHARE_SESSION_CREATED"
SHARE_SESSION_REVOKED = "SHARE_SESSION_REVOKED"
SHARE_OTP_REQUESTED = "SHARE_OTP_REQUESTED"
SHARE_AUTHENTICATED = "SHARE_AUTHENTICATED"
SHARE_AUTH_FAILURE = "SHARE_AUTH_FAILURE"
SHARE_VIEWED = "SHARE_VIEWED"
ACCESS_REQUESTED = "ACCESS_REQUESTED"
PERMISSION_GRANTED = "PERMISSION_GRANTED"
PERMISSION_DECLINED = "PERMISSION_DECLINED"

REPORT_UPLOADED = "REPORT_UPLOADED"
REPORT_UPLOAD_REJECTED = "REPORT_UPLOAD_REJECTED"
REPORT_PROCESSED = "REPORT_PROCESSED"
REPORT_PROCESSING_FAILED = "REPORT_PROCESSING_FAILED"
REPORT_VIEWED = "REPORT_VIEWED"

DOCTOR_PROFILE_REGISTERED = "DOCTOR_PROFILE_REGISTERED"
DOCTOR_VERIFIED = "DOCTOR_VERIFIED"
DOCTOR_PATIENT_VIEWED = "DOCTOR_PATIENT_VIEWED"
DOCTOR_PATIENT_RESULTS_VIEWED = "DOCTOR_PATIENT_RESULTS_VIEWED"

PRESCRIPTION_UPLOADED = "PRESCRIPTION_UPLOADED"
PRESCRIPTION_PROCESSED = "PRESCRIPTION_PROCESSED"
PRESCRIPTION_PROCESSING_FAILED = "PRESCRIPTION_PROCESSING_FAILED"
PRESCRIPTION_ITEM_CORRECTED = "PRESCRIPTION_ITEM_CORRECTED"
MEDICINE_CREATED = "MEDICINE_CREATED"
MEDICINE_UPDATED = "MEDICINE_UPDATED"

AI_EXPLAIN_REQUESTED = "AI_EXPLAIN_REQUESTED"
AI_COMPARE_REQUESTED = "AI_COMPARE_REQUESTED"
AI_DOCTOR_SUMMARY_REQUESTED = "AI_DOCTOR_SUMMARY_REQUESTED"
AI_CONVERSATION_CREATED = "AI_CONVERSATION_CREATED"
AI_CONVERSATION_MESSAGE_SENT = "AI_CONVERSATION_MESSAGE_SENT"

PERMISSION_ROLE_CREATED = "PERMISSION_ROLE_CREATED"
PERMISSION_ROLE_UPDATED = "PERMISSION_ROLE_UPDATED"
PERMISSION_ROLE_DELETED = "PERMISSION_ROLE_DELETED"
