"""initial schema

Revision ID: 2f7e72589d83
Revises: 
Create Date: 2026-08-10 09:49:25.820161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '2f7e72589d83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', app.db.types.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('event_metadata', app.db.types.JSONEncodedDict(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED', name='sex'), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('allergies', app.db.types.JSONEncodedDict(), nullable=False),
    sa.Column('current_medications', app.db.types.JSONEncodedDict(), nullable=False),
    sa.Column('emergency_contact', app.db.types.JSONEncodedDict(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('healthy_ids',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('healthy_id', sa.String(length=14), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_healthy_ids_healthy_id'), 'healthy_ids', ['healthy_id'], unique=True)
    op.create_table('sharing_sessions',
    sa.Column('patient_user_id', app.db.types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('recipient_identifier_encrypted', sa.String(), nullable=False),
    sa.Column('recipient_identifier_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharing_sessions_patient_user_id'), 'sharing_sessions', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_sharing_sessions_recipient_identifier_hash'), 'sharing_sessions', ['recipient_identifier_hash'], unique=False)
    op.create_index(op.f('ix_sharing_sessions_token_hash'), 'sharing_sessions', ['token_hash'], unique=True)
    op.create_table('user_identities',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('identity_type', sa.Enum('PHONE', 'EMAIL', name='identitytype'), nullable=False),
    sa.Column('identity_value_encrypted', sa.String(), nullable=False),
    sa.Column('identity_value_hash', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_type', 'identity_value_hash', name='uq_identity_lookup')
    )
    op.create_index(op.f('ix_user_identities_identity_value_hash'), 'user_identities', ['identity_value_hash'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('access_requests',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('requested_duration_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='accessrequeststatus'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sharing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_session_id'), 'access_requests', ['session_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('sharing_session_id', app.db.types.GUID(), nullable=True),
    sa.Column('identity_value_hash', sa.String(length=64), nullable=False),
    sa.Column('otp_code_hash', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['sharing_session_id'], ['sharing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_identity_value_hash'), 'otp_challenges', ['identity_value_hash'], unique=False)
    op.create_index(op.f('ix_otp_challenges_sharing_session_id'), 'otp_challenges', ['sharing_session_id'], unique=False)
    op.create_index(op.f('ix_otp_challenges_user_id'), 'otp_challenges', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('device_id', app.db.types.GUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('sharing_session_scopes',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sharing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'category', name='uq_scope_category')
    )
    op.create_index(op.f('ix_sharing_session_scopes_session_id'), 'sharing_session_scopes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sharing_session_scopes_session_id'), table_name='sharing_session_scopes')
    op.drop_table('sharing_session_scopes')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_otp_challenges_user_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_sharing_session_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_identity_value_hash'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_access_requests_session_id'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_identity_value_hash'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_sharing_sessions_token_hash'), table_name='sharing_sessions')
    op.drop_index(op.f('ix_sharing_sessions_recipient_identifier_hash'), table_name='sharing_sessions')
    op.drop_index(op.f('ix_sharing_sessions_patient_user_id'), table_name='sharing_sessions')
    op.drop_table('sharing_sessions')
    op.drop_index(op.f('ix_healthy_ids_healthy_id'), table_name='healthy_ids')
    op.drop_table('healthy_ids')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
