"""permission roles

Revision ID: 3badd6c34539
Revises: be9f13e6ef34
Create Date: 2026-08-23 13:49:46.702928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types

# revision identifiers, used by Alembic.
revision: str = '3badd6c34539'
down_revision: Union[str, None] = 'be9f13e6ef34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_roles',
    sa.Column('patient_user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_duration_hours', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_roles_patient_user_id'), 'permission_roles', ['patient_user_id'], unique=False)
    op.create_table('permission_role_scopes',
    sa.Column('role_id', app.db.types.GUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['permission_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'category', name='uq_role_scope_category')
    )
    op.create_index(op.f('ix_permission_role_scopes_role_id'), 'permission_role_scopes', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_role_scopes_role_id'), table_name='permission_role_scopes')
    op.drop_table('permission_role_scopes')
    op.drop_index(op.f('ix_permission_roles_patient_user_id'), table_name='permission_roles')
    op.drop_table('permission_roles')
    # ### end Alembic commands ###
