"""phase 4/5/6: doctor profiles, sharing doctor link, medicines, prescriptions

Revision ID: 7390280e3a0e
Revises: d63085311a79
Create Date: 2026-08-15 22:51:56.555823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '7390280e3a0e'
down_revision: Union[str, None] = 'd63085311a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='doctorverificationstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medicines',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prescribing_doctor', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_user_id'), 'medicines', ['user_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'SCANNING', 'PROCESSING', 'EXTRACTING', 'ANALYZING', 'COMPLETED', 'FAILED', name='prescription_processing_status'), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('ocr_engine', sa.String(length=100), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('prescribed_date', sa.Date(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_status'), 'prescriptions', ['status'], unique=False)
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('prescription_id', app.db.types.GUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('original_medicine_name', sa.String(length=200), nullable=True),
    sa.Column('original_dosage', sa.String(length=100), nullable=True),
    sa.Column('original_frequency', sa.String(length=100), nullable=True),
    sa.Column('original_duration', sa.String(length=100), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    # SQLite can't ALTER a constraint onto an existing table directly — batch
    # mode does the copy-and-move dance for us (this table has no data yet
    # in any real deployment of this migration, but batch mode is correct
    # either way, and this is the one portable way to add an FK on SQLite).
    with op.batch_alter_table('sharing_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_user_id', app.db.types.GUID(), nullable=True))
        batch_op.create_index(op.f('ix_sharing_sessions_doctor_user_id'), ['doctor_user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_sharing_sessions_doctor_user_id_users',
            'users',
            ['doctor_user_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharing_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sharing_sessions_doctor_user_id_users', type_='foreignkey')
        batch_op.drop_index(op.f('ix_sharing_sessions_doctor_user_id'))
        batch_op.drop_column('doctor_user_id')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_status'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medicines_user_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
